# chrooked:core
# Generated by chrooked-pokedex — do not hand-edit.
# Loads after all base scripts (ScriptLoader.rb loads patch/Mods/*.rb last),
# so Module#prepend wraps the vanilla battle methods: wrapper runs first,
# `super` runs the untouched vanilla code, then we adjust the result.
# Behavior files (chrooked_<id>.rb) only append entries to the registry
# tables below; all prepending happens here, once.

# attacker ability => ->(move, attacker, opponent) { Float multiplier }
CHROOKED_DAMAGE_MODS = {}
# move symbol => ->(move, attacker, opponent) { Float multiplier } — the
# move-keyed twin of CHROOKED_DAMAGE_MODS, for a move whose own damage scales on
# a condition (Short Circuit x2 vs paralyzed). Not a defender ability, so Mold
# Breaker never suppresses it.
CHROOKED_MOVE_DAMAGE_MODS = {}
# defender ability => ->(move, attacker, opponent) { Float multiplier on incoming damage }
CHROOKED_DEFENSE_MODS = {}
# attacker ability => ->(move, type) { new type Symbol or nil } — consulted by pbType
CHROOKED_TYPE_MODS = {}
# attacker ability => ->(battler, targets, basemove, battle) — after its move KOs
CHROOKED_ON_KO = {}
# attacker ability => ->(move, user, target, battle) — after dealing damage
CHROOKED_ON_DEAL = {}
# move symbol => ->(move, user, target, battle) — after this MOVE deals damage
CHROOKED_MOVE_ON_DEAL = {}
# defender ability => ->(move, user, target, battle) — after surviving a damaging hit
CHROOKED_WHEN_HIT = {}
# ability => ->(battler, battle) — on switch-in
CHROOKED_SWITCH_IN = {}
# ability => ->(battler, battle) — end of round while on the field
CHROOKED_TURN_END = {}
# ability => ->(battler) { Float multiplier } — effective Speed
CHROOKED_SPEED_MODS = {}
# ability => ->(move, attacker) { Integer priority delta }
CHROOKED_PRIORITY_MODS = {}
# defender ability => { type: Symbol, flag: Symbol } — :Soundproof blocks,
# :HpAbsorbAbility absorbs + heals 1/4 (both resolved by vanilla flag handling)
CHROOKED_TYPE_IMMUNITY = {}
# attacker ability => ->(move, attacker) { true } — use SpA in place of Atk for this hit
CHROOKED_STAT_SWAP = {}
# ability => ->(battler, move_symbol, battle) — after the battler used a move
CHROOKED_AFTER_MOVE = {}
# ability => weather Symbol — this battler's MOVES resolve weather as this (Mega Sol seam)
CHROOKED_WEATHER_FOR_USER = {}
# move symbol => ->(move, atype, attacker, opponent, typemod) { adjusted Typemod }
CHROOKED_MOVE_TYPEMOD = {}
# attacker ability => ->(move, atype, attacker, opponent, typemod) { adjusted Typemod }
# The ability-keyed twin of CHROOKED_MOVE_TYPEMOD. Needed when the matchup being
# rewritten is a 0x immunity: MOVE_TYPEMOD's multiply-by-(2/chart) trick cannot
# scale away from zero, so these handlers rebuild the whole Typemod slot by slot.
CHROOKED_ABILITY_TYPEMOD = {}
# attacker ability => ->(move, attacker) { true } — immune matchups become neutral
CHROOKED_TYPEMOD_FLOOR = {}
# attacker ability => ->(move, attacker) { true } — also bypass ability/levitation immunity hitflags
CHROOKED_IMMUNITY_BYPASS = {}
# ability => ->(battler, hpgain, agent) { adjusted hpgain } — drain/absorb heals
CHROOKED_ABSORB_MODS = {}
# move symbol => Float multiplier on the drain/absorb heal — the move-keyed twin
# of CHROOKED_ABSORB_MODS (a move whose OWN drain fraction differs from its
# funccode default, e.g. Reap/Siphon halve 0x0DD's 50% to a quarter drain).
CHROOKED_MOVE_ABSORB_MODS = {}
# [ability, move symbol] => Float fraction of max HP — fixed self-heal override
CHROOKED_HEAL_OVERRIDE = {}
# ability => ->(move, battler, target_kind) { new target kind or nil }
CHROOKED_TARGET_MODS = {}
# attacker ability => ->(move, attacker) { true } — skip the accuracy roll entirely
CHROOKED_SURE_HIT = {}
# attacker ability => ->(move, attacker, opponent) { float } — multiply final accuracy
CHROOKED_ACCURACY_MODS = {}
# ability => ->(battler, message) { true to cancel } — veto a vanilla HP tick the
# holder would otherwise take. The only seam for a drawback hardcoded mid-method
# (Solar Power's sun drain lives inside pbEndOfRoundPhase, no hook of its own).
CHROOKED_HP_LOSS_VETO = {}

module Chrooked
  # Rejuv has no hammer flag; keyed by move symbol (the hammer/slam set).
  HAMMER_MOVES = [:SLAM, :BODYSLAM, :HAMMERARM, :IRONHEAD, :WOODHAMMER,
                  :HEAVYSLAM, :ICEHAMMER, :GIGATONHAMMER].freeze
  # No piercing flag either; the horn/drill set from the Ruleset's flag data.
  # ponytail: covers Ruleset-flagged moves only — extend if a piercing move is missing in play.
  PIERCING_MOVES = [:DRILLPECK, :DRILLRUN, :FURYATTACK, :HORNATTACK, :HORNDRILL,
                    :HORNLEECH, :MEGAHORN, :PECK, :PSYCHOCUT, :PSYSHIELDBASH,
                    :SMARTSTRIKE].freeze
  # No wing flag; wind rides the native :windmove flag, wings ride this set.
  WING_MOVES = [:WINGATTACK, :DUALWINGBEAT, :BRAVEBIRD, :OBLIVIONWING,
                :ESPERWING, :AERIALACE].freeze

  def self.hammer_move?(move)
    HAMMER_MOVES.include?(move.move)
  end

  def self.piercing_move?(move)
    PIERCING_MOVES.include?(move.move)
  end

  def self.wing_or_wind_move?(move)
    WING_MOVES.include?(move.move) || move.windMove?
  end

  def self.kick_move?(move)
    move.hasFlag?(:kickmove)
  end

  # Moves whose type is computed by their own function code — never retyped by
  # an "-ize" ability (mirrors the mainline -ate exclusions).
  IZE_EXCLUDED = [:WEATHERBALL, :NATURALGIFT, :JUDGMENT, :TECHNOBLAST,
                  :MULTIATTACK, :REVELATIONDANCE, :TERRAINPULSE, :STRUGGLE].freeze

  def self.retypeable?(move)
    !move.zmove && !IZE_EXCLUDED.include?(move.move)
  end

  # True when the attacker's type-mod actually converts this move — the shared
  # predicate between pbType (the conversion) and the +20% damage rider.
  def self.type_changed?(move, attacker)
    mod = CHROOKED_TYPE_MODS[attacker.ability]
    return false unless mod && retypeable?(move)
    !mod.call(move, move.type).nil?
  end

  # One "-ize" ability = a Normal->X conversion plus a 1.2x damage rider.
  def self.register_ize(ability, to_type)
    CHROOKED_TYPE_MODS[ability] = lambda { |move, type|
      type == :NORMAL ? to_type : nil
    }
    CHROOKED_DAMAGE_MODS[ability] = lambda { |move, attacker, opponent|
      Chrooked.type_changed?(move, attacker) ? 1.2 : 1.0
    }
  end

  # 1.5 STAB grant when the move's effective type is in `types` but the user
  # does not carry that type (vanilla already paid STAB when it does).
  def self.stab_grant(move, attacker, types = nil)
    return 1.0 if move.basedamage.to_i <= 0 || move.move == :STRUGGLE
    type = move.pbType(attacker)
    return 1.0 if types && !types.include?(type)
    attacker.hasType?(type) ? 1.0 : 1.5
  end

  def self.damage_mult(move, attacker, opponent)
    mult = 1.0
    atk_mod = CHROOKED_DAMAGE_MODS[attacker.ability]
    mult *= atk_mod.call(move, attacker, opponent) if atk_mod
    # Move-keyed damage rider — a property of the move, so it rides with the
    # attacker side (never suppressed by the target's Mold Breaker).
    move_mod = CHROOKED_MOVE_DAMAGE_MODS[move.move]
    mult *= move_mod.call(move, attacker, opponent) if move_mod
    # Mold Breaker (and Teravolt/Turboblaze/Mycelium Might) ignore the TARGET's ability,
    # so defender-side mods must not apply. shouldBeMoldBroken? also honours Ability Shield
    # and sanity-checks the objects, so prefer it over the bare .moldbroken flag.
    # Attacker-side mods above are deliberately NOT suppressed — Mold Breaker never
    # disables the user's own ability.
    mold_broken = opponent.respond_to?(:shouldBeMoldBroken?) &&
                  opponent.shouldBeMoldBroken?(attacker, move)
    def_mod = opponent && !mold_broken && CHROOKED_DEFENSE_MODS[opponent.ability]
    mult *= def_mod.call(move, attacker, opponent) if def_mod
    mult
  end

  # Proof trail: one line per boosted hit in chrooked.log (game root).
  # ponytail: unconditional append, no rotation — file grows only when mods fire.
  def self.log(message)
    File.open("chrooked.log", "a") { |f| f.puts("#{Time.now.strftime('%H:%M:%S')} #{message}") }
  rescue StandardError
    nil
  end
end

module ChrookedDamageMods
  def pbCalcDamage(attacker, opponent, *args, **kwargs)
    swap = CHROOKED_STAT_SWAP[attacker.ability]
    if swap && swap.call(self, attacker)
      original_attack = attacker.attack
      attacker.attack = attacker.spatk
      begin
        dmg = super
      ensure
        attacker.attack = original_attack
      end
    else
      dmg = super
    end
    return dmg if !dmg.is_a?(Numeric) || dmg <= 0
    mult = Chrooked.damage_mult(self, attacker, opponent)
    return dmg if mult == 1.0
    boosted = (dmg * mult).round
    Chrooked.log("#{attacker.ability}/#{opponent ? opponent.ability : '-'} x#{mult.round(3)} #{@move}: #{dmg} -> #{boosted}")
    boosted
  end
end
PokeBattle_Move.prepend(ChrookedDamageMods)

module ChrookedTypeMods
  def pbType(attacker, type = @type)
    t = super
    mod = attacker && CHROOKED_TYPE_MODS[attacker.ability]
    if mod && Chrooked.retypeable?(self)
      new_type = mod.call(self, t)
      t = new_type if new_type
    end
    t
  end
end
PokeBattle_Move.prepend(ChrookedTypeMods)

module ChrookedMoveHooks
  def priorityCheck(attacker)
    pri = super
    mod = CHROOKED_PRIORITY_MODS[attacker.ability]
    pri += mod.call(self, attacker) if mod
    pri += 1 if attacker.effects[:ChrookedStampede] && contactMove?
    pri
  end

  def pbTypeImmunities(attacker, targets, hitflags, movetype: nil)
    super
    # ponytail: primary effective type only — dual-type moves keep vanilla handling.
    move_type = movetype || pbType(attacker)
    targets.each_with_index do |opponent, i|
      next if hitflags[i] != :Success
      next unless pbShouldApplyTypeImmunity?(attacker, opponent)
      immunity = CHROOKED_TYPE_IMMUNITY[opponent.ability]
      next unless immunity && !opponent.moldbroken
      hitflags[i] = immunity[:flag] if move_type == immunity[:type]
    end
    # Immunity bypass (Bonebreaker): re-open levitation/absorb-ability blocks.
    bypass = CHROOKED_IMMUNITY_BYPASS[attacker.ability]
    if bypass && bypass.call(self, attacker)
      reopened = [:Levitate, :AirBalloon, :MagnetRise, :Telekinesis,
                  :HpAbsorbAbility, :FlashFireAbility]
      hitflags.each_with_index do |flag, i|
        hitflags[i] = :Success if reopened.include?(flag)
      end
    end
  end

  def pbTypeModifier(atype, attacker, opponent)
    typemod = super
    # Ability-keyed pass runs BEFORE the move-keyed one, and the order is
    # load-bearing. An ability handler may rebuild a 0x matchup into a non-zero
    # one (Corrosion: Poison-vs-Steel 0x -> 2x); the move handlers scale a slot
    # by multiplication, which is a no-op against zero. Ability first means a
    # move override (Gastric Snare's Bug 2x) composes on top of the rebuilt
    # value instead of being silently discarded by it. Mold Breaker does not
    # suppress this — it is the ATTACKER's ability, not the defender's.
    amod = CHROOKED_ABILITY_TYPEMOD[attacker.ability]
    typemod = amod.call(self, atype, attacker, opponent, typemod) if amod
    mod = CHROOKED_MOVE_TYPEMOD[@move]
    typemod = mod.call(self, atype, attacker, opponent, typemod) if mod
    # Pure block immunities also zero the typemod so the AI's damage preview
    # and immunity checks see them (the hitflag alone is invisible to the AI).
    # Absorb-heal immunities stay hitflag-only — a zero typemod would skip the
    # heal. ponytail: AI stays blind to absorb-heals, same as it is to ours.
    opp_ability = opponent.shouldBeMoldBroken?(attacker, self) ? nil : opponent.ability
    immunity = opp_ability && CHROOKED_TYPE_IMMUNITY[opp_ability]
    if immunity && immunity[:flag] == :Soundproof && atype == immunity[:type]
      typemod = Typemod.zero
    end
    floor = CHROOKED_TYPEMOD_FLOOR[attacker.ability]
    if floor && typemod.immune? && floor.call(self, attacker)
      typemod = Typemod.normal
    end
    typemod
  end

  def pbAccuracyCheck(attacker, opponent)
    sure = CHROOKED_SURE_HIT[attacker.ability]
    return true if sure && sure.call(self, attacker)
    super
  end

  def pbCalcAccuracy(attacker, opponent)
    acc = super
    # -1 = perfect accuracy, 0 = auto-miss/Wonder Skin — leave both untouched.
    return acc if acc <= 0
    mod = CHROOKED_ACCURACY_MODS[attacker.ability]
    # ponytail: multiply the final accuracy instead of appending to the engine's
    # accmult array — one rounding step off from a native modifier, immaterial here.
    acc = (acc * mod.call(self, attacker, opponent)).round if mod
    acc
  end
end
PokeBattle_Move.prepend(ChrookedMoveHooks)

module ChrookedBattlerHooks
  def pbOnKillEffects(targets, basemove, *args)
    ret = super
    return ret if @battle.pbAnySideAllFainted? || self.isFainted?
    mod = CHROOKED_ON_KO[self.ability]
    mod&.call(self, targets, basemove, @battle)
    ret
  end

  def pbEffectsOnDealingDamage(move, user, target, damage, *args)
    ret = super
    return ret if damage.to_i <= 0 || target.damagestate.substitute
    atk_mod = CHROOKED_ON_DEAL[user.ability]
    atk_mod&.call(move, user, target, @battle) if !user.isFainted?
    move_mod = CHROOKED_MOVE_ON_DEAL[move.move]
    move_mod&.call(move, user, target, @battle) if !user.isFainted?
    # Same Mold Breaker rule as damage_mult: the target's ability is ignored, so its
    # when-hit reaction must not fire. Attacker-side mods above are unaffected.
    target_mold_broken = target.respond_to?(:shouldBeMoldBroken?) &&
                         target.shouldBeMoldBroken?(user, move)
    def_mod = target_mold_broken ? nil : CHROOKED_WHEN_HIT[target.ability]
    def_mod&.call(move, user, target, @battle) if !target.isFainted?
    ret
  end

  def pbAbilitiesOnSwitchIn(*args, **kwargs)
    ret = super
    mod = CHROOKED_SWITCH_IN[self.ability]
    mod&.call(self, @battle) if !self.isFainted?
    ret
  end

  def pbSpeed(*args)
    speed = super
    mod = CHROOKED_SPEED_MODS[self.ability]
    mod ? (speed * mod.call(self)).floor : speed
  end

  def pbUseMove(choice, *args, **kwargs)
    ret = super
    mod = CHROOKED_AFTER_MOVE[self.ability]
    mod&.call(self, self.lastMoveUsed, @battle) if mod && !self.isFainted? && self.lastMoveUsed.is_a?(Symbol)
    ret
  end

  def absorbHP(hpgain, opponent, agent, move = nil)
    mod = CHROOKED_ABSORB_MODS[self.ability]
    hpgain = mod.call(self, hpgain, agent) if mod
    # move-keyed drain fraction (the drain funccode passes the move as `move`).
    mmod = move ? CHROOKED_MOVE_ABSORB_MODS[move.move] : nil
    hpgain = (hpgain * mmod).round if mmod
    super
  end

  def pbReduceHP(amt, anim = false, emercheck = true, message: nil)
    veto = CHROOKED_HP_LOSS_VETO[self.ability]
    return 0 if veto && veto.call(self, message)
    super
  end

  def pbTarget(move)
    target = super
    mod = CHROOKED_TARGET_MODS[self.ability]
    if mod
      new_target = mod.call(move, self, target)
      target = new_target if new_target
    end
    target
  end
end
PokeBattle_Battler.prepend(ChrookedBattlerHooks)

module ChrookedBattleHooks
  def pbEndOfRoundPhase(*args, **kwargs)
    ret = super
    @battlers.each do |battler|
      next if !battler || battler.isFainted?
      mod = CHROOKED_TURN_END[battler.ability]
      mod&.call(battler, self)
    end
    ret
  end

  # Sage Power's Gorilla-Tactics-style lock. Vanilla keys its lock checks on
  # ability == :GORILLATACTICS, so the lock for other abilities is enforced
  # here at move selection. ponytail: sleep-talk/z-move edge cases keep
  # vanilla behavior (unlocked) — same ceiling as the AI's view of the lock.
  def pbCanChooseMove?(idxPokemon, idxMove, *args, **kwargs)
    allowed = super
    return allowed unless allowed
    # AI passes battler objects (and move objects) instead of indexes — mirror
    # vanilla's own coercion at the top of this method.
    battler = idxPokemon.is_a?(PokeBattle_Battler) ? idxPokemon : @battlers[idxPokemon]
    lock = battler && battler.effects[:ChrookedMoveLock]
    if lock && battler.moves.any? { |m| m && m.move == lock }
      basemove = idxMove.is_a?(PokeBattle_Move) ? idxMove : battler.moves[idxMove]
      return false if basemove && basemove.move != lock
    end
    allowed
  end

  # Per-user weather perception (Mega Sol's own seam): a battler whose ability
  # is registered sees its OWN moves resolve under that weather.
  def pbWeather(moveuser)
    forced = moveuser && CHROOKED_WEATHER_FOR_USER[moveuser.ability]
    return forced if forced
    super
  end
end
PokeBattle_Battle.prepend(ChrookedBattleHooks)

# Fixed-fraction self-heal override for the weather-heal moves
# (Synthesis / Moonlight / Morning Sun share function code 0x0D8).
if defined?(PokeBattle_Move_0D8)
  module ChrookedWeatherHealMods
    def pbEffect(attacker, alltargets, hitnum = 0)
      fraction = CHROOKED_HEAL_OVERRIDE[[attacker.ability, @move]]
      return super unless fraction
      hpgain = (attacker.totalhp * fraction).round
      attacker.pbRecoverHP(hpgain, true,
                           message: _INTL("{1} had its HP restored.", attacker.pbThis))
    end
  end
  PokeBattle_Move_0D8.prepend(ChrookedWeatherHealMods)
end
