# chrooked:core
# Generated by chrooked-pokedex — do not hand-edit.
# Loads after all base scripts (ScriptLoader.rb loads patch/Mods/*.rb last),
# so Module#prepend wraps the vanilla battle methods: wrapper runs first,
# `super` runs the untouched vanilla code, then we adjust the result.
# Behavior files (chrooked_<id>.rb) only append entries to the registry
# tables below; all prepending happens here, once.

# attacker ability => ->(move, attacker, opponent) { Float multiplier }
CHROOKED_DAMAGE_MODS = {}
# defender ability => ->(move, attacker, opponent) { Float multiplier on incoming damage }
CHROOKED_DEFENSE_MODS = {}
# attacker ability => ->(move, type) { new type Symbol or nil } — consulted by pbType
CHROOKED_TYPE_MODS = {}

module Chrooked
  # Rejuv has no hammer flag; keyed by move symbol (the hammer/slam set).
  HAMMER_MOVES = [:SLAM, :BODYSLAM, :HAMMERARM, :IRONHEAD, :WOODHAMMER,
                  :HEAVYSLAM, :ICEHAMMER, :GIGATONHAMMER].freeze
  # No piercing flag either; the horn/drill set from the Ruleset's flag data.
  # ponytail: covers Ruleset-flagged moves only — extend if a piercing move is missing in play.
  PIERCING_MOVES = [:DRILLPECK, :DRILLRUN, :FURYATTACK, :HORNATTACK, :HORNDRILL,
                    :HORNLEECH, :MEGAHORN, :PECK, :PSYCHOCUT, :PSYSHIELDBASH,
                    :SMARTSTRIKE].freeze
  # No wing flag; wind rides the native :windmove flag, wings ride this set.
  WING_MOVES = [:WINGATTACK, :DUALWINGBEAT, :BRAVEBIRD, :OBLIVIONWING,
                :ESPERWING, :AERIALACE].freeze

  def self.hammer_move?(move)
    HAMMER_MOVES.include?(move.move)
  end

  def self.piercing_move?(move)
    PIERCING_MOVES.include?(move.move)
  end

  def self.wing_or_wind_move?(move)
    WING_MOVES.include?(move.move) || move.windMove?
  end

  def self.kick_move?(move)
    move.hasFlag?(:kickmove)
  end

  # Moves whose type is computed by their own function code — never retyped by
  # an "-ize" ability (mirrors the mainline -ate exclusions).
  IZE_EXCLUDED = [:WEATHERBALL, :NATURALGIFT, :JUDGMENT, :TECHNOBLAST,
                  :MULTIATTACK, :REVELATIONDANCE, :TERRAINPULSE, :STRUGGLE].freeze

  def self.retypeable?(move)
    !move.zmove && !IZE_EXCLUDED.include?(move.move)
  end

  # True when the attacker's type-mod actually converts this move — the shared
  # predicate between pbType (the conversion) and the +20% damage rider.
  def self.type_changed?(move, attacker)
    mod = CHROOKED_TYPE_MODS[attacker.ability]
    return false unless mod && retypeable?(move)
    !mod.call(move, move.type).nil?
  end

  # One "-ize" ability = a Normal->X conversion plus a 1.2x damage rider.
  def self.register_ize(ability, to_type)
    CHROOKED_TYPE_MODS[ability] = lambda { |move, type|
      type == :NORMAL ? to_type : nil
    }
    CHROOKED_DAMAGE_MODS[ability] = lambda { |move, attacker, opponent|
      Chrooked.type_changed?(move, attacker) ? 1.2 : 1.0
    }
  end

  # 1.5 STAB grant when the move's effective type is in `types` but the user
  # does not carry that type (vanilla already paid STAB when it does).
  def self.stab_grant(move, attacker, types = nil)
    return 1.0 if move.basedamage.to_i <= 0 || move.move == :STRUGGLE
    type = move.pbType(attacker)
    return 1.0 if types && !types.include?(type)
    attacker.hasType?(type) ? 1.0 : 1.5
  end

  def self.damage_mult(move, attacker, opponent)
    mult = 1.0
    atk_mod = CHROOKED_DAMAGE_MODS[attacker.ability]
    mult *= atk_mod.call(move, attacker, opponent) if atk_mod
    def_mod = opponent && CHROOKED_DEFENSE_MODS[opponent.ability]
    mult *= def_mod.call(move, attacker, opponent) if def_mod
    mult
  end

  # Proof trail: one line per boosted hit in chrooked.log (game root).
  # ponytail: unconditional append, no rotation — file grows only when mods fire.
  def self.log(message)
    File.open("chrooked.log", "a") { |f| f.puts("#{Time.now.strftime('%H:%M:%S')} #{message}") }
  rescue StandardError
    nil
  end
end

module ChrookedDamageMods
  def pbCalcDamage(attacker, opponent, *args, **kwargs)
    dmg = super
    return dmg if !dmg.is_a?(Numeric) || dmg <= 0
    mult = Chrooked.damage_mult(self, attacker, opponent)
    return dmg if mult == 1.0
    boosted = (dmg * mult).round
    Chrooked.log("#{attacker.ability}/#{opponent ? opponent.ability : '-'} x#{mult.round(3)} #{@move}: #{dmg} -> #{boosted}")
    boosted
  end
end
PokeBattle_Move.prepend(ChrookedDamageMods)

module ChrookedTypeMods
  def pbType(attacker, type = @type)
    t = super
    mod = attacker && CHROOKED_TYPE_MODS[attacker.ability]
    if mod && Chrooked.retypeable?(self)
      new_type = mod.call(self, t)
      t = new_type if new_type
    end
    t
  end
end
PokeBattle_Move.prepend(ChrookedTypeMods)
