"""The composition mod: an ability built from several behaviors (#99).

Rejuvenation has ~1650 direct ``battler.ability == :X`` comparisons and no single
seam to intercept, so Redux Mode already solved "one ability behaves as several"
by swapping the battler's ability for a ``ChrookedAbilitySet`` whose ``==``
matches ANY owned symbol. This module reuses that class with a FIXED list.

Why a set rather than merged lambdas: vanilla pays its own riders on the part
symbols. Vanilla grants a 1.5x sun boost when ``ability == :SOLARPOWER``, so
Solar Power's chrooked lambda *corrects* that boost rather than paying it. A
combo built as a set containing ``:SOLARPOWER`` makes vanilla's check fire, which
restores the baseline the correcting lambda assumes. Merged lambdas would have to
redo that baseline maths per ability, which is exactly the drift #96 exists to
kill.

Accepted knowingly: a composed Pokemon genuinely IS each of its parts to every
vanilla branch, including unenumerated ones (there is a Desert-field interaction
at ``Scripts/Battle.rb:5487``). That is the intent, not a leak.

Load order: mods load alphabetically. This file must load AFTER
``chrooked_zz_redux.rb``, which defines ``ChrookedAbilitySet`` — and "compose"
sorts BEFORE "redux". Hence ``chrooked_zz_zcompose.rb``, which sorts last of
every chrooked mod on disk. Renaming it without re-checking that order silently
breaks composition into a no-op.
"""

from __future__ import annotations

from ...model.ruleset import Ruleset
from ...model.schema import composed_behaviors, is_composed

MOD_NAME = "chrooked_zz_zcompose.rb"

_HEADER = '''# encoding: utf-8
# chrooked:zz_zcompose
# Generated by chrooked-pokedex — do not hand-edit.
#
# A composed ability is one built from several behaviors. At battler init its
# symbol is replaced by a ChrookedAbilitySet of its parts, so every vanilla
# `ability == :PART` check fires and every chrooked table registered against a
# part is picked up by Chrooked.entries.
#
# This runs whether or not Redux Mode is on: composition is a property of the
# ability, not a game option. When Redux IS on the battler's ability is already
# a set, so we expand each member through the table and rebuild ONE FLAT set —
# ChrookedAbilitySet#== compares against `other.list`, so a nested set would
# never match.
#
# The filename sorts last on purpose. ChrookedAbilitySet is defined in
# chrooked_zz_redux.rb and "compose" would sort before "redux".
'''

_HOOK = '''
# Ability symbol => the part symbols it is built from.
CHROOKED_COMPOSITION = {
%(table)s}.freeze

module Chrooked
  # Every part symbol behind an ability, flattened one level. A plain symbol
  # that is not composed returns itself, so callers need no special case.
  def self.compose_parts(sym)
    CHROOKED_COMPOSITION[sym] || [sym]
  end

  # Build the battle-time ability for a mon. `owned` is whatever the engine (or
  # Redux Mode) put there: a bare Symbol, or a ChrookedAbilitySet.
  def self.composed_ability(owned)
    return owned if owned.nil?
    members = owned.respond_to?(:list) ? owned.list : [owned]
    flat = members.flat_map { |m| compose_parts(m) }.compact.uniq
    return owned if flat.length <= 1 && !owned.respond_to?(:list)
    return owned if flat == members
    set = ChrookedAbilitySet.new(flat)
    # The set matches AS its parts but is CALLED by the ability the mon actually
    # has — two different questions that must not share an answer. Redux's set
    # has no display identity, so leave it alone and only stamp a composed one.
    if set.respond_to?(:chrooked_display=) && !owned.respond_to?(:list)
      set.chrooked_display = owned
    end
    set
  end
end

if defined?(PokeBattle_Battler)
  class PokeBattle_Battler
    if method_defined?(:pbInitPokemon) && !method_defined?(:chrooked_compose_init)
      alias_method :chrooked_compose_init, :pbInitPokemon
      def pbInitPokemon(pkmn, pkmnIndex)
        chrooked_compose_init(pkmn, pkmnIndex)
        built = Chrooked.composed_ability(@ability)
        return if built.equal?(@ability)
        @ability = built
        # changeAbility restores from @backupability once suppression ends —
        # keep the full set there so Gastro Acid wearing off re-arms it.
        @backupability = built
      end
    end
  end
end
'''


def render_compose_mod(ruleset: Ruleset) -> str:
    """The Ruby source for ``patch/Mods/chrooked_zz_zcompose.rb``.

    Emitted on every apply, even with no composed abilities, so a target never
    keeps a stale table from a previous run — apply does not prune mods.
    """
    rows: list[str] = []
    for chrooked_id in sorted(ruleset.abilities):
        ability = ruleset.abilities[chrooked_id]
        if not is_composed(ability):
            continue
        parts = ", ".join(
            _symbol(ruleset, part) for part in composed_behaviors(ability)
        )
        rows.append(f"  {_symbol(ruleset, chrooked_id)} => [{parts}],\n")
    table = "".join(rows)
    return _HEADER + (_HOOK % {"table": table})


def _symbol(ruleset: Ruleset, chrooked_id: str) -> str:
    """The Rejuv Ruby symbol for an id.

    Prefers an explicit ``aka.essentials``/``aka.rejuv`` hint when the Ruleset
    carries one, and otherwise upper-cases the id — which is how every other
    Rejuv symbol in this applier is derived.
    """
    ability = ruleset.abilities.get(chrooked_id)
    if ability is not None:
        for key in ("rejuv", "essentials"):
            hint = ability.aka.get(key)
            if isinstance(hint, str) and hint:
                return f":{hint}"
    return ":" + "".join(ch for ch in chrooked_id.upper() if ch.isalnum())
