"""Serialize Python values to Ruby literals and build the three delta files.

A *delta file* is a small Ruby script that first evals the game's own base
definition file (so ``MONHASH``/``MOVEHASH``/``ABILHASH`` are fully populated),
then assigns individual fields. This keeps the patch tiny (one line per changed
field) and update-proof: a base-game change to an untouched species passes
through verbatim.

Every species assignment block is wrapped in a ``dig`` guard so a base update
that removes a form degrades to a console note instead of crashing the compiler.
"""

from __future__ import annotations

# A Symbol wrapper: emit() renders these as ``:NAME`` (bare Ruby symbols),
# distinct from strings which render quoted.
class Sym:
    __slots__ = ("name",)

    def __init__(self, name: str) -> None:
        self.name = name


def to_ruby(value: object) -> str:
    """Render a Python value as a Ruby literal.

    ``Sym("GRASS")`` -> ``:GRASS``; ``"hi"`` -> ``"hi"``; ``None`` -> ``nil``;
    lists/tuples nest (movesets are lists of ``[level, Sym]`` pairs).
    """
    if value is None:
        return "nil"
    if isinstance(value, Sym):
        return f":{value.name}"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(to_ruby(v) for v in value) + "]"
    raise TypeError(f"cannot serialize {type(value).__name__} to Ruby: {value!r}")


_HEADER = (
    "# Generated by chrooked-pokedex — do not hand-edit.\n"
    "# Delete the patch/ directory to uninstall every change.\n"
)


def _mon_ref(key: str, form: str) -> str:
    return f'MONHASH[:{key}]["{form}"]'


def montext_delta(assignments: list[tuple[str, str, list[str]]]) -> str:
    """Build ``patch/Definitions/montext.rb``.

    ``assignments`` is a list of ``(key, form, statements)`` where each statement
    is a complete Ruby line (e.g. ``MONHASH[:KEY]["FORM"][:BaseStats][3] = 130``).
    Each species is wrapped in a dig guard so a base update that drops the form
    degrades to a console note instead of a crash.
    """
    out = [_HEADER, 'eval(File.read("Scripts/Rejuv/Definitions/montext.rb"), TOPLEVEL_BINDING)', ""]
    for key, form, statements in assignments:
        out.append(f'if MONHASH.dig(:{key}, "{form}")')
        for stmt in statements:
            out.append(f"  {stmt}")
        out.append("else")
        out.append(f'  puts "chrooked: skipped {key} {form} (missing in base montext)"')
        out.append("end")
        out.append("")
    return "\n".join(out)


def _hash_delta(const: str, base_file: str, blocks: list[str]) -> str:
    out = [
        _HEADER,
        f'eval(File.read("Scripts/Rejuv/Definitions/{base_file}"), TOPLEVEL_BINDING)',
        "",
    ]
    out.extend(blocks)
    return "\n".join(out) + ("\n" if blocks else "")


def movetext_delta(blocks: list[str]) -> str:
    """Build ``patch/Definitions/movetext.rb`` from ready MOVEHASH statement lines."""
    return _hash_delta("MOVEHASH", "movetext.rb", blocks)


def abiltext_delta(blocks: list[str]) -> str:
    """Build ``patch/Definitions/abiltext.rb`` from ready ABILHASH statement lines."""
    return _hash_delta("ABILHASH", "abiltext.rb", blocks)

def typetext_delta(blocks: list[str]) -> str:
    """Build ``patch/Definitions/typetext.rb`` from ready TYPEHASH statement lines."""
    return _hash_delta("TYPEHASH", "typetext.rb", blocks)
