"""The Ruby source for ``patch/Init/chrooked_compile.rb``.

Rejuv only auto-compiles a ``.dat`` when it is MISSING (see ``Scripts/Cache.rb``),
and the base ``Data/*.dat`` always exist, so dropping delta files into
``patch/Definitions/`` alone would change nothing at boot. This Init script —
which the engine runs before the main menu — forces a recompile of exactly the
categories whose delta file is newer than its compiled output. Because a patch
definition exists, the compiler's ``data_directory`` already routes output to
``patch/Data/``; we call the compile helpers with no directory argument.

Kept as a Python string so tests can assert on the emitted text without a Ruby
interpreter (the game ships no standalone Ruby; the real compile is proven by one
in-game boot).
"""

from __future__ import annotations

INIT_SCRIPT = '''# Generated by chrooked-pokedex — do not hand-edit.
# Recompile patched definitions when they are newer than the compiled output.
# Fallback if this ever runs too early: open the in-game debug console, run "compiledata".
begin
  # The compiler writes patch/Data/*.dat but does not create the folder.
  Dir.mkdir("patch/Data") unless File.directory?("patch/Data")
  pairs = [
    ["patch/Definitions/montext.rb", "patch/Data/mons.dat", :compileMons],
    ["patch/Definitions/movetext.rb", "patch/Data/moves.dat", :compileMoves],
    ["patch/Definitions/abiltext.rb", "patch/Data/abil.dat", :compileAbilities],
    ["patch/Definitions/typetext.rb", "patch/Data/types.dat", :compileTypes],
  ]
  pairs.each do |defn, dat, fn|
    next unless File.exist?(defn)
    stale = !File.exist?(dat) || File.mtime(defn) > File.mtime(dat)
    next unless stale
    send(fn)
  end
rescue => e
  dp("chrooked compile failed: #{e.message}") if defined?(dp)
end
'''
